on: [workflow_dispatch ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: true
      - uses: arduino/cpp-test-action@v1
        with:
          runtime-paths: "- extras/test/build/arduino_DS1881_2-tests"
